package uaigroup.mapservice.model;

public enum EventType {
    BATTLE_STARTED,
    BATTLE_ENDED,
    UNIT_CREATED,
    UNIT_MOVED,
    UNIT_ATTACKED,
    UNIT_DESTROYED,
    UNIT_DAMAGED,
    UNIT_HEALED,
    ACTION_STARTED,
    ACTION_COMPLETED,
    ACTION_FAILED,
    SCRIPT_ACTIVATED,
    SCRIPT_COMPLETED,
    COMMS_ESTABLISHED,
    COMMS_LOST,
    OBSTACLE_CREATED,
    OBSTACLE_DESTROYED
}
